[project]
name = 'hyperinsure'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.clarity-bitcoin]
path = 'contracts/clarity-bitcoin.clar'
clarity_version = 3
epoch = '3.0'

[contracts.insurance-treasury-v2]
path = 'contracts/insurance-treasury-v2.clar'
clarity_version = 3
epoch = '3.2'

[contracts.policy-manager]
path = 'contracts/policy-manager.clar'
clarity_version = 3
epoch = '3.2'

[contracts.claim-processor]
path = 'contracts/claim-processor.clar'
clarity_version = 3
epoch = '3.2'
depends_on = ["clarity-bitcoin", "insurance-treasury-v2", "policy-manager"]

[contracts.oracle]
path = 'contracts/oracle.clar'
clarity_version = 3
epoch = '3.2'
depends_on = ["clarity-bitcoin"]

[contracts.governance]
path = 'contracts/governance.clar'
clarity_version = 3
epoch = '3.2'

[contracts.hyperinsure-core]
path = 'contracts/hyperinsure-core.clar'
clarity_version = 3
epoch = '3.2'
depends_on = ["oracle", "governance"]

[contracts.hyperinsure-core-v2]
path = 'contracts/hyperinsure-core-v2.clar'
clarity_version = 3
epoch = '3.2'
depends_on = ["clarity-bitcoin"]

[contracts.frontend-api]
path = 'contracts/frontend-api.clar'
clarity_version = 3
epoch = '3.2'
depends_on = ["insurance-treasury-v2", "policy-manager", "claim-processor"]
[repl.analysis]
passes = ['check_checker']

# [contracts.simple-insurance]
# path = 'contracts/simple-insurance.clar'
# clarity_version = 3
# epoch = '3.2'


[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = true
api_url = 'https://api.hiro.so'
initial_height = 595050
